global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    datacenter: primary

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager-0-27.alpha-prod.svc.cluster.local:9093

rule_files:
  - /opt/bitnami/prometheus/conf/rules.yaml
  - /opt/bitnami/prometheus/conf/alerts.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '192.168.157.157:9100'
          - '192.168.159.15:9100'
          - '192.168.154.103:9100'
          - '192.168.143.10:9100'
          - '192.168.156.164:9100'
          - '192.168.156.121:9100'
          - '192.168.156.102:9100'
          - '192.168.130.243:9100'
          - '192.168.143.189:9100'
          - '192.168.162.26:9100'
          - '192.168.143.177:9100'
          - '192.168.186.72:9100'
          - '192.168.198.209:9100'
          - '192.168.143.102:9100'
          - '192.168.131.99:9100'
          - '192.168.130.246:9100'
          - '192.168.143.202:9100'
          - '192.168.186.229:9100'
          - '192.168.197.242:9100'
          - '192.168.170.127:9100'
          - '192.168.170.235:9100'
          - '192.168.197.251:9100'
          - '192.168.191.171:9100'
          - '192.168.170.113:9100'
          - '192.168.143.125:9100'
          - '192.168.135.34:9100'
          - '192.168.170.97:9100'
          - '192.168.170.110:9100'
          - '192.168.134.10:9100'
          - '192.168.150.151:9100'
          - '192.168.197.65:9100'
          - '192.168.140.207:9100'
          - '192.168.140.175:9100'
          - '192.168.193.189:9100'
          - '192.168.193.12:9100'
          - '192.168.193.238:9100'
          - '192.168.193.191:9100'
          - '192.168.169.205:9100'
          - '192.168.169.58:9100'
          - '192.168.169.39:9100'
          - '192.168.169.30:9100'
          - '192.168.144.66:9100'
          - '192.168.159.53:9100'
          - '192.168.197.219:9100'
          - '192.168.156.171:9100'
          - '192.168.156.108:9100'
          - '192.168.147.233:9100'
          - '192.168.157.239:9100'
          - '192.168.193.41:9100'
          - '192.168.147.84:9100'
          - '192.168.147.226:9100'
          - '192.168.145.176:9100'
          - '192.168.138.132:9100'
          - '192.168.197.154:9100'
          - '192.168.141.200:9100'
          - '192.168.175.162:9100'
          - '192.168.180.18:9100'
          - '192.168.209.112:9100'
          - '192.168.175.85:9100'
          - '192.168.175.184:9100'
          - '192.168.209.210:9100'
          - '192.168.142.145:9100'
          - '192.168.143.9:9100'
          - '192.168.210.94:9100'
          - '192.168.147.6:9100'
          - '192.168.144.220:9100'
    metric_relabel_configs:
      - source_labels: ['nodename']
        regex: '(vv.master)'
        target_label: nodename
        replacement: vv-${1}
      - source_labels: ['nodename']
        regex: 'vv.worker.node.(.*)'
        target_label: nodename
        replacement: vv-${1}

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

  - job_name: 'clickhouse'
    static_configs:
      - targets:
          - 'clickhousecluster-25-6-0.clickhousecluster-25-6.viralvue-prod.svc.cluster.local:9363'
          - 'clickhousecluster-25-6-1.clickhousecluster-25-6.viralvue-prod.svc.cluster.local:9363'
          - 'clickhousecluster-25-6-2.clickhousecluster-25-6.viralvue-prod.svc.cluster.local:9363'
          - 'clickhousecluster-25-6-3.clickhousecluster-25-6.viralvue-prod.svc.cluster.local:9363'
          - 'clickhousecluster-25-6-4.clickhousecluster-25-6.viralvue-prod.svc.cluster.local:9363'
          - 'clickhousecluster-25-6-5.clickhousecluster-25-6.viralvue-prod.svc.cluster.local:9363'
          - 'clickhousecluster-25-6-6.clickhousecluster-25-6.viralvue-prod.svc.cluster.local:9363'
          - 'clickhousecluster-25-6-7.clickhousecluster-25-6.viralvue-prod.svc.cluster.local:9363'
          - 'clickhousecluster-25-6-8.clickhousecluster-25-6.viralvue-prod.svc.cluster.local:9363'

  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels:
          - __meta_kubernetes_node_name
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        
  - job_name: 'kubernetes-kubelet'
    scheme: https
    metrics_path: /metrics
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics
        
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

