global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alert-manager-0-27:9093

rule_files:
   - /opt/bitnami/prometheus/conf/rules.yaml
   - /opt/bitnami/prometheus/conf/alerts.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['172.16.70.4:9100']
    metric_relabel_configs:
      - source_labels: ['nodename']
        regex: '(engine.master)'
        target_label: nodename
        replacement: appz-${1}
      - source_labels: ['nodename']
        regex: 'k8s.worker.node.(.*)'
        target_label: nodename
        replacement: appz-dev-worker-${1}
  
  - job_name: 'kube-state-metrics'
    static_configs:
    - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
    
  - job_name: 'windows_server'
    metrics_path: /metrics
    static_configs:
    - targets: ['172.16.40.20:9182']
      labels:
        instance: 'UnityTest01'
    - targets: ['172.16.2.8:9182']
      labels:
        instance: 'UnityDC2'
    - targets: ['10.5.1.4:9182']
      labels:
        instance: 'UNITYSQLSVR003'
    - targets: ['172.16.30.12:9182']
      labels:
        instance: 'UNITYSQLSVR002'
    - targets: ['172.16.10.26:9182']
      labels:
        instance: 'UNITYWEB02'
    - targets: ['172.16.30.11:9182']
      labels:
        instance: 'UNITYSQLSVR001'
    - targets: ['172.16.10.20:9182']
      labels:
        instance: 'UNITYWEB01'
    - targets: ['172.16.40.10:9182']
      labels:
        instance: 'UnityOps01'
    - targets: ['172.16.20.4:9182']
      labels:
        instance: 'EZD01'
    - targets: ['172.16.2.6:9182']
      labels:
        instance: 'UnityDC'

  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      
