global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager-0-27:9093

rule_files:
  - /opt/bitnami/prometheus/conf/rules.yaml
  - /opt/bitnami/prometheus/conf/alerts.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 192.168.155.101:9100
          - 192.168.151.227:9100
          - 192.168.144.216:9100   
          - 172.234.144.12:9100
          - 172.234.136.73:9100
          - 192.168.176.96:9100
          - 192.168.168.69:9100
          - 192.168.168.198:9100
          - 192.168.168.210:9100
          - 192.168.171.196:9100
          - 192.168.129.186:9100
          - 192.168.183.33:9100
          - 192.168.171.230:9100
          - 192.168.162.187:9100
          - 192.168.169.82:9100
          - 192.168.183.152:9100
          - 192.168.129.173:9100
          - 192.168.147.133:9100
          - 192.168.183.13:9100
          - 192.168.129.112:9100
          - 192.168.183.131:9100
          - 192.168.129.249:9100
          - 192.168.154.187:9100
          - 192.168.164.213:9100
          - 192.168.129.98:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: 192.168.155.101:9100
        target_label: nodename
        replacement: Ti-prod-worker-0
      - source_labels: [__address__]
        regex: 192.168.151.227:9100
        target_label: nodename
        replacement: Ti-prod-worker-1
      - source_labels: [__address__]
        regex: 192.168.144.216:9100
        target_label: nodename
        replacement: Ti-prod-worker-2
      - source_labels: [__address__]
        regex: 172.234.144.12:9100
        target_label: nodename
        replacement: prod-engine-master
      - source_labels: [__address__]
        regex: 172.234.136.73:9100
        target_label: nodename
        replacement: VPN-Server-Prod
      - source_labels: [__address__]
        regex: 192.168.176.96:9100
        target_label: nodename
        replacement: mysql-prod-node-0
      - source_labels: [__address__]
        regex: 192.168.168.69:9100
        target_label: nodename
        replacement: kafka-node-0
      - source_labels: [__address__]
        regex: 192.168.168.198:9100
        target_label: nodename
        replacement: kafka-node-1
      - source_labels: [__address__]
        regex: 192.168.168.210:9100
        target_label: nodename
        replacement: kafka-node-2
      - source_labels: [__address__]
        regex: 192.168.183.13:9100
        target_label: nodename
        replacement: chart-app-node-0
      - source_labels: [__address__]
        regex: 192.168.129.186:9100
        target_label: nodename
        replacement: chart-app-node-1
      - source_labels: [__address__]
        regex: 192.168.183.33:9100
        target_label: nodename
        replacement: chart-app-node-2
      - source_labels: [__address__]
        regex: 192.168.183.131:9100
        target_label: nodename
        replacement: chart-app-node-3
      - source_labels: [__address__]
        regex: 192.168.171.196:9100
        target_label: nodename
        replacement: MariaDB-node-0
      - source_labels: [__address__]
        regex: 192.168.171.230:9100
        target_label: nodename
        replacement: MariaDB-node-1
      - source_labels: [__address__]
        regex: 192.168.162.187:9100
        target_label: nodename
        replacement: oddsmaker-node-0
      - source_labels: [__address__]
        regex: 192.168.169.82:9100
        target_label: nodename
        replacement: market-explorer-node-0
      - source_labels: [__address__]
        regex: 192.168.183.152:9100
        target_label: nodename
        replacement: fasalert-node-0
      - source_labels: [__address__]
        regex: 192.168.129.173:9100
        target_label: nodename
        replacement: mysql-slave-replica-0
      - source_labels: [__address__]
        regex: 192.168.147.133:9100
        target_label: nodename
        replacement: ai-feed-node-0
      - source_labels: [__address__]
        regex: 192.168.129.112:9100
        target_label: nodename
        replacement: mysql-slave-replica-1
      - source_labels: [__address__]
        regex: 192.168.129.249:9100
        target_label: nodename
        replacement: mysql-slave-replica-2
      - source_labels: [__address__]
        regex: 192.168.154.187:9100
        target_label: nodename
        replacement: ai-feed-node-1
      - source_labels: [__address__]
        regex: 192.168.164.213:9100
        target_label: nodename
        replacement: wordpress-node-0    
      - source_labels: [__address__]
        regex: 192.168.129.98:9100
        target_label: nodename
        replacement: mysql-slave-replica-3
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

  - job_name: 'kubernetes-kubelet'
    scheme: https
    metrics_path: /metrics
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  - job_name: 'windows_server'
    metrics_path: /metrics
    static_configs:
    - targets: ['172.239.142.27:9182']
      labels:
        instance: 'windows-server'

  - job_name: 'kafka-exporter'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_run]
      regex: kafka-cluster-4-0
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex: "9308"
      action: keep
    - source_labels: [__meta_kubernetes_pod_ip]
      target_label: __address__
      replacement: ${1}:9308
      action: replace
    - target_label: component
      replacement: kafka
 
  - job_name: 'kafka_jmx'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_run]
      regex: kafka-cluster-4-0
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex: "9404"
      action: keep
    - source_labels: [__meta_kubernetes_pod_ip]
      target_label: __address__
      replacement: ${1}:9404
      action: replace
    - target_label: component
      replacement: kafka-jmx

  - job_name: 'mariadb-master-exporter'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_run]
      regex: mariadb-master-chart-10-11
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex: "9104"
      action: keep
    - source_labels: [__meta_kubernetes_pod_ip]
      target_label: __address__
      replacement: ${1}:9104
      action: replace
    - target_label: instance
      replacement: mariadb-master
    - target_label: role
      replacement: master
    - target_label: db_engine
      replacement: mariadb

  - job_name: 'mariadb-slave-exporter'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_run]
      regex: mariadb-slave-chart-10-11
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex: "9104"
      action: keep
    - source_labels: [__meta_kubernetes_pod_ip]
      target_label: __address__
      replacement: ${1}:9104
      action: replace
    - target_label: slave_id
      replacement: mariadb-slave-10-11
    - target_label: instance
      replacement: mariadb-slave-10-11
    - target_label: role
      replacement: slave
    - target_label: db_engine
      replacement: mariadb
  
  #- job_name: 'mysql_slave'
  #  metrics_path: /metrics
  #  static_configs:
   #   - targets: ['10.2.2.139:9104']
      #  labels:
    #      role: slave  
  - job_name: 'mysql-slave-exporter'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_run]
      regex: mysql-slave-8-0
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex: "9104"
      action: keep
    - source_labels: [__meta_kubernetes_pod_ip]
      target_label: __address__
      replacement: ${1}:9104
      action: replace
    - target_label: slave_id
      replacement: mysql-slave
    - target_label: instance
      replacement: mysql-slave
    - target_label: role
      replacement: slave
    - target_label: db_engine
      replacement: mysql

  - job_name: 'mysql-slave-replica-exporter-0'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_name]
      regex: mysql-replicas-8-0-0
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex: "9104"
      action: keep
    - source_labels: [__meta_kubernetes_pod_ip]
      target_label: __address__
      replacement: ${1}:9104
      action: replace
    - target_label: slave_id
      replacement: mysql-replicas-0
    - target_label: instance
      replacement: mysql-replicas-0
    - target_label: role
      replacement: slave-replicas
    - target_label: db_engine
      replacement: mysql-replicas

  - job_name: 'mysql-slave-replica-exporter-1'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_name]
      regex: mysql-replicas-8-0-1
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex: "9104"
      action: keep
    - source_labels: [__meta_kubernetes_pod_ip]
      target_label: __address__
      replacement: ${1}:9104
      action: replace
    - target_label: slave_id
      replacement: mysql-replicas-1
    - target_label: instance
      replacement: mysql-replicas-1
    - target_label: role
      replacement: slave-replicas
    - target_label: db_engine
      replacement: mysql-replicas

  - job_name: 'mysql-slave-replica-exporter-2'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_name]
      regex: mysql-replicas-8-0-2
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex: "9104"
      action: keep
    - source_labels: [__meta_kubernetes_pod_ip]
      target_label: __address__
      replacement: ${1}:9104
      action: replace
    - target_label: slave_id
      replacement: mysql-replicas-2
    - target_label: instance
      replacement: mysql-replicas-2
    - target_label: role
      replacement: slave-replicas
    - target_label: db_engine
      replacement: mysql-replicas
      
  - job_name: 'app_db_health'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['mysql-healthcheck-3-11:5000/health/db']

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter-0-2:9115

  - job_name: 'tcp_connect_check'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets: ['192.168.155.101:31192']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter-0-2:9115

  - job_name: 'windows_rdp_tcp_check'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - '172.239.142.27:3389'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        replacement: windows-server
      - target_label: __address__
        replacement: blackbox-exporter-0-2:9115

  - job_name: 'windows_exporter_http_check'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - 'http://172.239.142.27:9182/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        replacement: windows-server
      - target_label: __address__
        replacement: blackbox-exporter-0-2:9115
